version: '3.1'

services:
  db:
    container_name: db_javalee_postgres
    image: postgres
    volumes:
      - pg_data:/data
    restart: always
    environment:
      - POSTGRES_DB=db_javalee
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=javalee
    ports:
      - 5432:5432
volumes:
  pg_data:
